import static app.cash.redwood.buildsupport.TargetGroup.CommonWithAndroid

redwoodBuild {
  targets(CommonWithAndroid)
  publishing()
}

apply plugin: 'org.jetbrains.kotlin.plugin.compose'
apply plugin: 'org.jetbrains.kotlin.plugin.serialization'
apply plugin: 'dev.drewhamilton.poko'

kotlin {
  sourceSets {
    commonMain {
      dependencies {
        implementation libs.androidx.compose.runtime
        implementation libs.kotlinx.serialization.core
        compileOnly 'io.github.tret9:zipline-bridge-annotations:1.28.0-composelive-0.4-SNAPSHOT'
      }
    }
    commonTest {
      dependencies {
        implementation libs.kotlin.test
        implementation libs.assertk
      }
    }
  }
}

dependencies {
  kotlinCompilerPluginClasspath 'io.github.tret9:zipline-bridge-kotlin-plugin:1.28.0-composelive-0.4-SNAPSHOT'
  constraints {
    commonMainApi("org.jetbrains.compose.runtime:runtime:1.9.0") {
      because('AndroidX publishes multiplatform version. The JetBrains artifact is now empty.')
    }
  }
}

android {
  namespace = 'app.cash.redwood.runtime'
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinJvmCompile).configureEach {
  compilerOptions.freeCompilerArgs.addAll(
    '-P', "plugin:app.cash.zipline.bridge.kotlin:cOutputDir=${buildDir}/generated/bridge/c",
  )
}
tasks.named('compileKotlinJvm').configure {
  outputs.dir("${buildDir}/generated/bridge/c")
}

kotlin.sourceSets.jsMain {
  kotlin.srcDir("${buildDir}/generated/bridge/c")
}
tasks.named('compileKotlinJs').configure { dependsOn('compileKotlinJvm') }

spotless {
  kotlin {
    targetExclude(
      // Apache 2-licensed files from AOSP.
      "src/commonMain/kotlin/app/cash/redwood/Modifier.kt",
    )
  }
}
